sudo: required
language: php
cache:
  bundler: true
  apt: true
  directories:
  - "$HOME/.composer/cache"
services:
  - docker
php:
  - 7
mysql:
  database: drupal
  username: root
  encoding: utf8
env:
  - MIGRATE=ck2
  - MIGRATE=uc6
matrix:
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version
  - docker-compose build
  - docker-compose up -d

  # Add Composer's local bin directory to the PATH so that we will be running
  # our installed versions of Drush, Phing, Behat, etc.
  - export PATH="$TRAVIS_BUILD_DIR/vendor/bin:$PATH"

  # Let Composer do all the magic!
  - composer install --no-interaction

  - phing install

script:
  - if [[ "$MIGRATE" == "ck2" ]]; then phing migrate-ck2; fi
  - if [[ "$MIGRATE" == "uc6" ]]; then phing migrate-uc6; fi
  # @todo run behat tests against the migrations
